<!DOCTYPE html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <link rel="shortcut icon" href="/favicon.ico" type="image/vnd.microsoft.icon"/>
  <title>Georgia Tech</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style type="text/css" media="all">
    @import url("/css/blocks.css");
    @import url("/css/content.css");
    @import url("/css/default.css");
    @import url("/css/editor.css");
    @import url("/css/hg_reader.css");
    @import url("/css/layout.css");
    @import url("/css/reset.css");
    @import url("/css/static.css");
    @import url("/css/typography.css");
    @import url('https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i');
    @import url('https://fonts.googleapis.com/css?family=Roboto+Slab:400,700');
    @import url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css')
  </style>
  <style type="text/css" media="print"> @import url("/css/print.css") </style>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
  <script type="text/javascript" src="/js/gt.js"></script>
</head>